# Generated by Django 2.0.3 on 2018-03-10 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('strong_against', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beat', to='game.Move')),
                ('weak_against', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beaten_by', to='game.Move')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='game.Game')),
                ('move_player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movel_player_1', to='game.Move')),
                ('move_player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movel_player_2', to='game.Move')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_winner', to='game.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='game.Player'),
        ),
    ]
